######################## default configuration ####################
baseURL = "http://TMC-academy.netlify.app/"
title = "TMC academy"
theme = "bigspring"
languageName = "En"
languageCode = "en-us"
# post pagination
paginate = "3"
# post excerpt
summaryLength = "15"
# disqus short name
disqusShortname = "" # get your shortname form here : https://disqus.com
# google analytics
googleAnalytics = "" # example : UA-123-45
# unsafe html
[markup.goldmark.renderer]
unsafe = true

############################# Plugins ##############################

# CSS Plugins
[[params.plugins.css]]
link = "plugins/bootstrap/bootstrap.min.css"
[[params.plugins.css]]
link = "plugins/themify-icons/themify-icons.css"
[[params.plugins.css]]
link = "plugins/slick/slick.css"

# JS Plugins
[[params.plugins.js]]
link = "plugins/jQuery/jquery.min.js"
[[params.plugins.js]]
link = "plugins/bootstrap/bootstrap.min.js"
[[params.plugins.js]]
link = "plugins/slick/slick.min.js"


############################## navigation ###############################

# main menu


[[menu.main]]
name = "Home"
URL = "#"
weight = 1

[[menu.main]]
name = "About Us"
URL = "about"
weight = 2

[[menu.main]]
name = "Our Programs"
URL = "#"
weight = 3

[[menu.main]]
name = "Team"
URL = "#"
weight = 4

[[menu.main]]
name = "Contact"
URL = "contact"
weight = 5



# footer menu left
[[menu.footer_left]]
name = "Our Services"
URL = "about"
weight = 1

[[menu.footer_left]]
name = "Our Partners"
URL = "about"
weight = 2

[[menu.footer_left]]
name = "Our Team"
URL = "about"

[[menu.footer_left]]
name = "Our Events"
URL = "about"



# footer menu middle
[[menu.footer_middle]]
name = "Donate in Honor"
URL = "#"

[[menu.footer_middle]]
name = "Provide us a Laptop"
URL = "#"

[[menu.footer_middle]]
name = "Become a Mentor"
URL = "#"

[[menu.footer_middle]]
name = "Become a Volunteer"
URL = "#"



# footer menu right
[[menu.footer_right]]
name = "Diversity Statement"
URL = "diversity-statement"
weight = 1

[[menu.footer_right]]
name = "Code of Conduct"
URL = "coc"
weight = 2

[[menu.footer_right]]
name = "FAQs"
URL = "faq"
weight = 3

[[menu.footer_right]]
name = "Blogs"
URL = "blog"


#################### default parameters ################################
[params]
logo = "images/logo.png"
logo_width = "200px"
# Meta data
description = "This is meta description"
author = "ali26.dev"
# contact form action
contact_form_action = "#" # contact form works with https://formspree.io

########### footer content ##########
footer_menu_left = "About Us"
footer_menu_middle = "Support"
footer_menu_right = "Non Profit"
footer_content = "Support cause you care about."
# copyright
copyright = "Designed and Maintained by [Ali26](https://ali26.com/)"

# Preloader
[params.preloader]
enable = false
preloader = "" # use jpg, png, svg or gif format.

# Navigation buttons
[params.navigation_button]
enable = true
label = "Donate Us"
link = "#"

  
############################# social site ########################
[[params.social]]
title = "facebook"
icon = "ti-facebook" # themify icon : https://themify.me/themify-icons
link = "#"

[[params.social]]
title = "twitter"
icon = "ti-twitter-alt" # themify icon : https://themify.me/themify-icons
link = "#"

[[params.social]]
title = "skype"
icon = "ti-skype" # themify icon : https://themify.me/themify-icons
link = "#"

[[params.social]]
title = "linkedin"
icon = "ti-linkedin" # themify icon : https://themify.me/themify-icons
link = "#"
